# Generated by Django 3.0.2 on 2020-01-12 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meme', '0002_remove_meme_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='owner',
        ),
    ]
